# Generated by Django 5.0.6 on 2024-07-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrun',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
